---
title: "Analyze Prioritization"
author: Anna L Tyler
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    code_folding: hide
    collapsed: no
    toc: yes
    toc_float: yes
bibliography: eae.bib
---


## Introduction

The purpose of this workflow is to analyze the 
results of Prioritization.Rmd

```{r setup}
rm(list = ls())
library(here)
```

```{r load_code}
all.fun <- list.files(here("Code"), full.names = TRUE, pattern = ".R")
for(i in 1:length(all.fun)){source(all.fun[i])}
```

```{r load_libraries}
needed.libraries <- c("pheatmap") 
load_libraries(needed.libraries)
```

```{r load_data}
qtl.genes <- read.csv(here("Results", "Prioritization", "qtl_candidates.csv")) #Generated by Prioritization.Rmd

all.nets <- get.files(here("Results", "Prioritization"), want = "", dont.want = ".csv")
net.results <- lapply(all.nets, function(x) read.csv(here("Results", "Prioritization", x, 
    "QTL_prioritization", "Module1", "Candidate.Gene.Results.csv")))
names(net.results) <- all.nets
```

## Compare Functional Scores

The following heat map compares the functional scores (-log10(FPR))
across all tissue networks. 

```{r comb_heat, fig.width = 5, fig.height = 7}
ranked.genes <- qtl.genes[,"external_gene_name"]
all.fpr <- matrix(NA, nrow = length(ranked.genes), ncol = length(all.nets))
rownames(all.fpr) <- ranked.genes
colnames(all.fpr) <- all.nets
for(i in 1:length(all.nets)){
    gene.idx <- match(ranked.genes, net.results[[i]][,"external_gene_name"])
    all.fpr[,i] <- -log10(net.results[[i]][gene.idx,"Mean.FP.Rate"])
}

fake.mat <- all.fpr
fake.mat[which(is.na(all.fpr))] <- 0
row.order <- hclust(dist(fake.mat))$order
pheatmap(all.fpr[row.order,], display_numbers = TRUE, cluster_rows = FALSE, cluster_cols = FALSE)
```